name: learn-github-actions
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: | 
            mkdir test
            cd test
            git clone git@github.com:Gautamaggrawal/Recipe-API.git
            echo "deployement of droplet success"
